### ISSUE TITLE
Don't copy files into system directories

### ISSUE THREAD

**Issue by enedil** [GideonWolfe/Zathura-Pywal#1]
This is a major drawback. Why shouldn't you want a dedicated directory in your homedir?

**Comment by GideonWolfe** [comment]
Sorry, I'm not sure I understand the question. Are you asking about the location of the configuration files or the executables?

**Comment by enedil** [comment]
I mean specifically this line from the install script: `# Run as root, this will add the scripts to your path`. If whole program can be run with user privileges, I don't see any reason for requiring root, especially given that nonetheless, this is some third party software by "nobody" (sorry for this).

**Comment by GideonWolfe** [comment]
Have you read the script? It just copies the script into `/usr/bin/` so it can be executed from anywhere. I could change it to `usr/local/bin`, but that would require root still to copy it there. You would even need root to add a symlink. It's just a couple commands, so run them yourself if you don't like the script :)

**Comment by GideonWolfe** [comment]
Thanks to @927589452 for fixing this issue in #3 and #2
