### ISSUE TITLE
suggestion change name to zathura

### ISSUE THREAD

**Issue by 927589452** [GideonWolfe/Zathura-Pywal#9]
Link to the real zathura in the file and let it replace zathura for all other applications
This requires all option being passed to the internals zathura call

**Comment by GideonWolfe** [comment]
Any hints on how to go about this?

Do you mean symlinking to the zathura executable?

**Comment by 927589452** [comment]
I was thinking of either changing the `$PATH` back to something not user based in the script or calling the "real" zathura by full path eg `/usr/local/bin/zathura`
